### PR TITLE
cross compile binaries for osx and linux

### PR DESCRIPTION
**Pull request by nicolaifsf**
Binaries for osx and linux
GOOS darwin 
GOOS linux
both GOARCH amd64

### CODE REVIEW

**Comment by jer** [comment]
👍 nice

**Comment by stjohnjohnson** [comment]
Nice, but you need to change the publish step to publish both.

**Comment by stjohnjohnson** [comment]
LGTM 👍

**Comment by nicolaifsf** [comment]
merging

**Pull request merged**
