### PR TITLE
Add deprecation warning

### PR DESCRIPTION
**Pull request by r3rastogi**
This repo isn't really used or maintained anymore, so this PR adds a note that warns people of this.

### CODE REVIEW

**Comment by tkyi** [comment]
Oh no Wercker build failed. It's so old we don't have a Screwdriver build for it. :[

**Comment by r3rastogi** [comment]
Yeah, I have no idea how to fix that :P

**Comment by minzcmu** [comment]
@r3rastogi to fix it: 

- get rid of the werker.yml
- delete the wercker webhook for this repo
- create a screwdriver pipeline

**Comment by r3rastogi** [comment]
Thanks @minz1027 !
* Removed the weker.yml
* Deleted the webhook
* Created https://cd.screwdriver.cd/pipelines/268

**Review by petey — APPROVED** [review]

**Review by minzcmu — APPROVED** [review]
👍

**Pull request merged**
